server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://nevada.integrity.com.ua:5432/audit
    password: PeQnubWRZHSZY8g
    driver-class-name: org.postgresql.Driver
    username: audit

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    rest:
      base-path: /api