server:
  port: 9000

spring:
  datasource:
    url: jdbc:oracle:thin:@//ibadz.iv.local:1521/IBAFN
    password: ibaaudit01
    driver-class-name: oracle.jdbc.OracleDriver
    username: ibaaudit

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    rest:
      base-path: /api